#!/usr/bin/env bash
# --------------------------------
# Script     : javar
# Description: it's used to run a java project easilier, you can use it in the src folder or in the project's root
# Version    : 0.3
# Author     : Ireras F. <ferreirasdemelo@gmail.com> 
# Date       : 16/08/2025
# License    : GNU/GPL v3.0
# --------------------------------
# Use: javar 
# --------------------------------


#[[ $# -ne 0 ]] && echo "Parameters are not required." && exit 1

[[ ! -f Main.java ]] && [[ ! -d src ]]  && echo "File Main.java doesn't exist and a src directory was not found." && exit 1

[[ -d src ]] && cd src && javac -d ../bin *.java && echo "Compiled!" && clear && cd ..  && java -cp "bin:lib/*" Main "$@" && exit 0
[[ -f Main.java ]] && clear && javac -d ../bin *.java && echo "Compiled!" && clear && cd .. && java -Dfile.encoding=UTF-8 -cp "bin:lib/*" Main "$@" && exit 0

#[[ -d src ]] && cd src && clear &&  find . -name "*.java" > sources.txt && javac -d ../bin -cp "lib/*" @sources.txt && echo "Compiled!" && clear && cd ..  && java -cp "bin:lib/*" Main && exit 0

#javac -d ../bin -cp "../lib/*" Main.java && cd .. && cd ./bin && java Main && exit 0
#javac Main.java && mv Main.class .. && cd .. && [[ -d bin ]] && mv Main.class ./bin && cd ./bin && java Main && exit 0

#[[ ! -d bin ]] && mkdir ./bin && mv Main.class ./bin && cd ./bin && java Main && exit 0
